version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update
      - sudo apt install nodejs -y
      - sudo apt install npm -y
      - sudo apt install zip -y
      
    build:
      commands:
        - echo "Building dependencies"
        - npm install
        - npm run build
        - sudo zip -r artifact.zip build
        - sudo rm -r !(artifact.zip))
    post_build:
      commands:
      - echo "Build has been successfully built"

artifacts:
  files:
    - "**/*"
