version: 0.2

phases:
    pre_build:
      commands:
        - npm install
        - apt install zip -y
    build:
      commands:
        - npm run build
        
    post_build:
      commands:
      - echo "lets go"
      
artifacts:
    files: 
      - build/*

