version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update
      - sudo apt install nodejs -y
      - sudo apt install npm -y
      - sudo apt install zip -y
      
      
    pre-build:
      commands:
        - sudo npm install
        - npm run build
    build:
      commands:
        - echo "Building dependencies"
        
    post_build:
      commands:
      - echo "Build has been successfully built"


artifacts:
  files:
    - build/**/*
